#!/bin/bash -v
# To be use on a vagrant machine
# prepare environment for librarian-puppet
if [ -d /vagrant ] ; then PUPPET_DIR=/vagrant ; else PUPPET_DIR=/etc/puppet ; fi
cd $PUPPET_DIR
time sudo librarian-puppet install
